site_name: Homeroom Wiki
repo_url: https://github.com/longbow122/homeroom-docs
repo_name: longbow122/homeroom-docs
plugins:
  - search:
      lang: en
theme:
  icon:
    repo: fontawesome/brands/github
  font:
    code: PT Mono  
  name: material
  logo: homeroom.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight