site_name: Homeroom Wiki
repo_url: https://github.com/longbow122/Homeroom
repo_name: Homeroom on GitHub
plugins:
  - search:
      lang: en
theme:
  icon:
    repo: fontawesome/brands/github
  font:
    code: PT Mono  
  name: material
  logo: homeroom.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
markdown_extensions:
  - attr_list
  - abbr
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav: #The top navigaton bar of the wiki page.
  - Home: "index.md"
  - User Documentation: "userHome.md"
  - Administrator Documentation: "adminHome.md"
  - Contributing: "contributors.md"