#This entire yml file was generaterd using Material for MkDocs
site_name: Homeroom Wiki
repo_url: https://github.com/longbow122/Homeroom
repo_name: Homeroom on GitHub
plugins:
  - search:
      lang: en
theme:
  icon:
    repo: fontawesome/brands/github
  font:
    code: PT Mono  
  name: material
  logo: homeroom.png
  favicon: homeroom.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - abbr
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav: #The top navigaton bar of the wiki page.
  - Home: "index.md"
    - Features: "features.md"
    - For Teachers: "informationForTeachers.md"
    - For Admins: "informationForAdmins.md"
  - User Documentation: "userDocumentation/userHome.md"
  - Administrator Documentation: "adminDocumentation/adminHome.md"
  - Contributing: "contributors.md" 
extra:
  generator: false 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/longbow122
      name: longbow122 on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://uk.linkedin.com/in/dhruvil-patel-072a01233
      name: Dhruvil Patel on LinkedIn  